nmct.ba.cashlessproject.api/Controllers/API/VerenigingController.cs
using nmct.ba.cashlessproject.api.Models.DA;
using nmct.ba.cashlessproject.model.Model.Costumer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Claims;
using System.Web.Http;

namespace nmct.ba.cashlessproject.api.Controllers.API
{
    public class VerenigingController : ApiController
    {
        public HttpResponseMessage Post(Vereniging ver)
        {
            VerenigingDA.InsertVereniging(ver);

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        public HttpResponseMessage Put(Vereniging ver)
        {
            ClaimsPrincipal cp = RequestContext.Principal as ClaimsPrincipal;
            VerenigingDA.UpdatePassword(cp.Claims, ver);

            return new HttpResponseMessage(HttpStatusCode.OK);
        }
    }
}

nmct.ba.cashlessproject.api/Controllers/VerenigingController.cs
using nmct.ba.cashlessproject.api.Models.DA;
using nmct.ba.cashlessproject.model.Model.Costumer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace nmct.ba.cashlessproject.api.Controllers
{
    [Authorize]
    public class VerenigingController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Overzicht()
        {
            List<Vereniging> listorganisations = VerenigingDA.GetOrganisations();
            ViewBag.ListOrganisations = listorganisations;
            return View();
        }

        [HttpGet]
        public ActionResult Registreren()
        {
            Vereniging vereniging = new Vereniging();
            return View(vereniging);
        }

        [HttpPost]
        public ActionResult InsertVereniging(Vereniging newOrganisation)
        {
            if (newOrganisation != null)
            {
                VerenigingDA.InsertVereniging(newOrganisation);

                return RedirectToAction("Overzicht");
            }
            else
            {
                return RedirectToAction("Error");
            }

        }

        public ActionResult Error()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Details(int orgId)
        {
            if(orgId != null && orgId != 0)
            {
                Vereniging ver = VerenigingDA.GetOrganisationById(orgId);

                return View(ver);
            }
            else
            {
                return View("Error");
            }
        }

        [HttpGet]
        public ActionResult EditVereniging(int orgId)
        {
            if (orgId != null && orgId != 0)
            {
                Vereniging ver = VerenigingDA.GetOrganisationById(orgId);

                return View(ver);
            }
            else
            {
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult UpdateVereniging(Vereniging ver)
        {
            if(ver != null)
            {
                VerenigingDA.UpdateVereniging(ver);
                return RedirectToAction("Overzicht");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

nmct.ba.cashlessproject.api/Views/Vereniging/Details.cshtml
@model nmct.ba.cashlessproject.model.Model.Costumer.Vereniging

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vereniging</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrganisationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganisationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

    </dl>
</div>
<p>
    <a href="/Vereniging/EditVereniging?OrgId=@Model.Id">Bewerken</a> |
    @Html.ActionLink("Terug naar overzicht", "Overzicht")
</p>

nmct.ba.cashlessproject.api/Views/Vereniging/EditVereniging.cshtml
@model nmct.ba.cashlessproject.model.Model.Costumer.Vereniging

@{
    ViewBag.Title = "EditVereniging";
}

<h2>EditVereniging</h2>

@using (Html.BeginForm("UpdateVereniging", "Vereniging", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vereniging</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.OrganisationName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrganisationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganisationName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar overzicht", "Overzicht")
</div>

nmct.ba.cashlessproject.api/Views/Vereniging/Index.cshtml
@{
    ViewBag.Title = "Verenigingen";
}

<h2>Verenigingen</h2>
<div class="row">
    <div class="col-md-4">
        <h2>Overzicht</h2>
        <p><a class="btn btn-default" href="http://localhost:1428/Vereniging/Overzicht">Overzicht verenigingen &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Registreren</h2>
        <p><a class="btn btn-default" href="http://localhost:1428/Vereniging/Registreren">Registreer vereniging &raquo;</a></p>
    </div>
</div>

nmct.ba.cashlessproject.api/Views/Vereniging/Overzicht.cshtml
@{
    ViewBag.Title = "Overzicht verenigingen";
}

<h2>Overzicht verenigingen</h2>
<table style="width:100%">
    <tr>
        <th>Naam</th>
    </tr>
    @foreach (var file in ViewBag.ListOrganisations)
    {
        <tr>
            <td>@file.OrganisationName</td>
            <td><a href="/Vereniging/Details?OrgId=@file.Id">Details</a></td>
        </tr>
    }

</table>

nmct.ba.cashlessproject.api/Views/Vereniging/Registreren.cshtml
@model nmct.ba.cashlessproject.model.Model.Costumer.Vereniging

@{
    ViewBag.Title = "Registreren";
}

<h2>Registreren</h2>

@using (Html.BeginForm("InsertVereniging", "Vereniging", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vereniging</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OrganisationName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrganisationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganisationName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DbName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DbName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DbName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DbLogin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DbLogin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DbLogin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DbPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DbPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DbPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aanmaken" class="btn btn-default" />
            </div>
        </div>
    </div>
}