nmct.ba.cashlessproject.api/Controllers/KassaController.cs
using nmct.ba.cashlessproject.api.Models.DA;
using nmct.ba.cashlessproject.api.Models.Presentation;
using nmct.ba.cashlessproject.model.Model.Costumer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace nmct.ba.cashlessproject.api.Controllers
{
    [Authorize]    
    public class KassaController : Controller
    {
        List<Register> allregisters = RegisterDA.GetRegisters();
        List<Vereniging> allorganisations = VerenigingDA.GetOrganisations();

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Link()
        {
            PMKassa pmkassa = new PMKassa();
            pmkassa.ListOrganisations = allorganisations;
            pmkassa.ListRegisters = allregisters;
            pmkassa.ListAvailableRegisters = new List<Register>();

            foreach (Register reg in allregisters)
            {
                bool isAvailableRegister = RegisterOrganisationDA.IsAvailableRegister(reg.Id);

                if (isAvailableRegister)
                {
                    pmkassa.ListAvailableRegisters.Add(reg);
                }
            }

            return View(pmkassa);
        }

        [HttpPost]
        public ActionResult LinkKassa(string kassa, string vereniging)
        {
            if(!string.IsNullOrEmpty(kassa) && !string.IsNullOrEmpty(vereniging))
            {
                Vereniging selectedVereniging = VerenigingDA.GetOrganisationById(Convert.ToInt32(vereniging));
                Register selectedRegister = RegisterDA.GetRegisterById(Convert.ToInt32(kassa));

                RegisterOrganisationDA.LinkRegisterToOrganisation(selectedRegister, selectedVereniging);

                return RedirectToAction("Link");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        [HttpGet]
        public ActionResult Overzicht()
        {
            PMKassa pmkassa = new PMKassa();
            pmkassa.ListOrganisations = allorganisations;
            pmkassa.ListRegisters = allregisters;
            pmkassa.ListAvailableRegisters = new List<Register>();

            foreach(Register reg in allregisters)
            {
                bool isAvailableRegister = RegisterOrganisationDA.IsAvailableRegister(reg.Id);

                if(isAvailableRegister)
                {
                    pmkassa.ListAvailableRegisters.Add(reg);
                }
            }

            return View(pmkassa);
        }

        [HttpPost]
        public ActionResult Overzicht(string vereniging)
        {
            PMKassa pmkassa = new PMKassa();
            pmkassa.ListRegisters = RegisterDA.GetRegisterPerOrganisation(Convert.ToInt32(vereniging));
            pmkassa.ListOrganisations = allorganisations;
            pmkassa.ListAvailableRegisters = new List<Register>();

            foreach (Register reg in allregisters)
            {
                bool isAvailableRegister = RegisterOrganisationDA.IsAvailableRegister(reg.Id);

                if (isAvailableRegister)
                {
                    pmkassa.ListAvailableRegisters.Add(reg);
                }
            }

            return View(pmkassa);
        }

        [HttpGet]
        public ActionResult Toevoegen()
        {
            Register register = new Register();
            return View(register);
        }

        [HttpGet]
        public ActionResult Wijzig(string RegisterId)
        {
            ViewBag.ChangeRegister = RegisterDA.GetRegisterById(Convert.ToInt32(RegisterId));
            ViewBag.ListOrganisations = allorganisations;

            return View();
        }

        [HttpPost]
        public ActionResult WijzigKassa(string changeregisterid, string vereniging)
        {
            if(!string.IsNullOrEmpty(changeregisterid) && !string.IsNullOrEmpty(vereniging))
            {
                Vereniging selectedVereniging = VerenigingDA.GetOrganisationById(Convert.ToInt32(vereniging));
                Register selectedRegister = RegisterDA.GetRegisterById(Convert.ToInt32(changeregisterid));

                //RegisterOrganisationDA.LinkRegisterToOrganisation(selectedRegister, selectedVereniging);

                return RedirectToAction("Overzicht");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Error()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ToevoegenKassa(Register register)
        {
            if(register != null)
            {
                RegisterDA.InsertRegister(register);

                return RedirectToAction("Overzicht");
            }
            else
            {
                return RedirectToAction("Error");
            } 
        }
    }
}

nmct.ba.cashlessproject.api/Views/Kassa/Index.cshtml
@{
    ViewBag.Title = "Kassa's";
}

<h2>Kassa's</h2>
<div class="row">
    <div class="col-md-4">
        <h2>Overzicht kassa's</h2>
        <p><a class="btn btn-default" href="http://localhost:1428/Kassa/Overzicht">Overzicht beschikbare kassa's &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Kassa toevoegen</h2>
        <p><a class="btn btn-default" href="http://localhost:1428/Kassa/Toevoegen">Voeg kassa toe &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Kassa aan vereniging linken</h2>
        <p><a class="btn btn-default" href="http://localhost:1428/Kassa/Link">Link kassa aan vereniging &raquo;</a></p>
    </div>
</div>

nmct.ba.cashlessproject.api/Views/Kassa/Link.cshtml
@model nmct.ba.cashlessproject.api.Models.Presentation.PMKassa

@{
    ViewBag.Title = "Link";
}

<h2>Link kassa</h2>
<form action="/Kassa/LinkKassa" method="post">
    <label for="kassa">Kassa</label>
    <br />
    <select name="kassa">
        @foreach (var kassa in Model.ListAvailableRegisters)
        {
            <option value="@kassa.Id">@kassa.RegisterName</option>
        }
    </select>
    <br />
    <br />
    <label for="vereniging">Vereniging</label>
    <br />
    <select name="vereniging">
        @foreach (var vereniging in Model.ListOrganisations)
        {
            <option value="@vereniging.Id">@vereniging.OrganisationName</option>
        }
    </select>
    <br />
    <br />
    <input type="submit" value="Link" name="btnLink" />
</form>

nmct.ba.cashlessproject.api/Views/Kassa/Overzicht.cshtml
@model nmct.ba.cashlessproject.api.Models.Presentation.PMKassa

@{
    ViewBag.Title = "Overzicht kassa's";
}

<h2>Overzicht kassa's</h2>
<br />
<br />
<form action="/Kassa/Overzicht" method="post">
    <select name="vereniging">
        @foreach (var vereniging in Model.ListOrganisations)
        {
            <option value="@vereniging.Id">@vereniging.OrganisationName</option>
        }
    </select>
    <br />
    <br />
    <input type="submit" value="Opzoeken" />
</form>
<br />
<br />
<h3>Beschikbare kassa's</h3>
<br />
<table style="width:100%">
    <tr>
        <th>Naam</th>
        <th>Toestel</th>
        <th>Aankoopdatum</th>
        <th>Verloopdatum</th>
    </tr>

    @foreach (var kassa in Model.ListAvailableRegisters)
    {
        <tr>
            <td>@kassa.RegisterName</td>
            <td>@kassa.Device</td>
            <td>@kassa.PurchaseDate</td>
            <td>@kassa.ExpiresDate</td>
        </tr>
    }
</table>
<br />
<br />
<h3>Kassa's</h3>
<br />
<table style="width:100%">
    <tr>
        <th>Naam</th>
        <th>Toestel</th>
        <th>Aankoopdatum</th>
        <th>Verloopdatum</th>
    </tr>

    @foreach (var kassa in Model.ListRegisters)
    {
        <tr>
            <td>@kassa.RegisterName</td>
            <td>@kassa.Device</td>
            <td>@kassa.PurchaseDate</td>
            <td>@kassa.ExpiresDate</td>
            <td><a href="/Kassa/Wijzig?RegisterId=@kassa.Id">Wijzig van vereniging</a></td>
        </tr>
    }
</table>
<br />
<br />
@Html.ActionLink("Toon alle kassa's", "Overzicht")

nmct.ba.cashlessproject.api/Views/Kassa/Toevoegen.cshtml
@model nmct.ba.cashlessproject.model.Model.Costumer.Register

@{
    ViewBag.Title = "Toevoegen";
}

<h2>Toevoegen</h2>

@using (Html.BeginForm("ToevoegenKassa", "Kassa", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Register</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RegisterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegisterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegisterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Device, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Device, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Device, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aanmaken" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Overzicht")
</div>

nmct.ba.cashlessproject.api/Views/Kassa/Wijzig.cshtml
@{
    ViewBag.Title = "Wijzig";
}

<h2>Wijzig kassa van vereniging</h2>
<form action="/Kassa/WijzigKassa" method="post">
    <label for="kassa">Kassa</label>
    <br />
    <p>@ViewBag.ChangeRegister.RegisterName</p>
    <input type="hidden" name="changeregisterid" value="@ViewBag.ChangeRegister.Id"/>
    <br />
    <label for="vereniging">Vereniging</label>
    <br />
    <select name="vereniging">
        @foreach (var vereniging in ViewBag.ListOrganisations)
        {
            <option value="@vereniging.Id">@vereniging.OrganisationName</option>
        }
    </select>
    <br />
    <br />
    <input type="submit" value="Wijzig" name="btnWijzig" />
</form>